INSERT INTO system_module (company_name, company_display_name, system_name, system_display_name, module, is_deleted) VALUES
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'RFQ', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Order', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Dispatch', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Shipment', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Invoice', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Supplier PO Verification', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Report', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Receipt', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Payment Request', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Ledger', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Voucher', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Invoice Verification', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Warehouse', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Incoming Invoice', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Categories', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Brand', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Product', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Bulk Order', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Jobwork', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Work Order', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Payment Tracker', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Configurations', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Loc', false),
	('OFBUSINESS', 'OfBusiness', 'OASYS', 'Oasys', 'Other', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Supplier', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'LSP', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Vendor', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Agent', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Buyer', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Lead', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Collection', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Research Lead', false),
	('OFBUSINESS', 'OfBusiness', 'OFB_SALES_SYSTEM', 'OFB Sales System', 'Other', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'PartnerConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'EscrowDocuments', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'FactoringInvoice', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LenderPaymentRequest', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'NamespacePermission', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanApplicationCorrespondence', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'OxyzoDocESign', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Feedback', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'NodeSubnodeConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'GstReturnSalesData', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'BankAlertPayment', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Promoter', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanCollections', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'ScfAnchorVendorMapping', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'OfferTnc', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Dashboard', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'RbiDirectiveMIS', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'AdhocLimit', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'PhysicalDocumentStorage', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Repos', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'RiskReport', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'BankAccountAutoAssignmentConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanDisbursements', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'EntityAccess', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Nbfc', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'DerivedRatios', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Document', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'TaxReturn', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Login', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Scorecard', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'CreditFactor', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Covenant', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Audit', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'PartnerMonitor', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'FixedDeposit', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'PaymentRequest', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'AllLedgers', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'AssetConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Correspondence', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'MiscellaneousConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Checklist', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Nach', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'RiskMonitoring', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Module2', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'UnderwritingReport', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'CallRecord', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'BankingMetrics', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Anchor', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanSheet', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'KycTracker', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Asset', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanLedgers', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanLcBoe', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Insurance', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Reports', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanApplication', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Bonds', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'NegativeBeneficiary', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Ecl', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'UnverifiedDocs', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanSecurity', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanDocuments', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'CreditRating', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'RequestForDisbursal', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanLap', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'BankAccount', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'ScfAnchorOpportunity', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Salesobservation', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'NbfcPartner', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'ProcessCibilData', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanCorrespondence', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'EmiSchedule', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'IncomingInvoice', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'AssetLiability', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Task', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Dsa', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Hypothecation', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'InsuranceManagement', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'ClientLoanSheet', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'OfferTermsAndConditions', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanBg', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Loan', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'DocumentType', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LegalContract', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'FloatingRates', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'DisbursementDocuments', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Lender', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanApplicationContact', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Client', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'SalesRegister', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'EquifaxPermission', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'AdhocAutoApprovalConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'ScfAnchor', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanAutoApprovalConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'VendorPaymentRequest', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'ReportsStats', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'KycConfig', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'DsaPayoutPaymentRequest', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Fldg', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Approval', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'FinancialMetrics', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'JobMonitor', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Probe', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanLC', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Underwriting', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Form', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Pd', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanRequest', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Cheque', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Invoice', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanPostSanctionChecklist', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'LoanLimitUtilisation', false),
	('OFBUSINESS', 'OfBusiness', 'ORION', 'Orion', 'Other', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO_SALES_SYSTEM', 'Oxyzo Sales System', 'Lead', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO_SALES_SYSTEM', 'Oxyzo Sales System', 'Collection', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO_SALES_SYSTEM', 'Oxyzo Sales System', 'Research Lead', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO_SALES_SYSTEM', 'Oxyzo Sales System', 'Lead Pipeline', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO_SALES_SYSTEM', 'Oxyzo Sales System', 'Other', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'PartnerConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'EscrowDocuments', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'FactoringInvoice', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LenderPaymentRequest', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'NamespacePermission', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanApplicationCorrespondence', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'OxyzoDocESign', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Feedback', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'NodeSubnodeConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'GstReturnSalesData', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'BankAlertPayment', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Promoter', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanCollections', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'ScfAnchorVendorMapping', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'OfferTnc', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Dashboard', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Module', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'RbiDirectiveMIS', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'AdhocLimit', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'PhysicalDocumentStorage', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Repos', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'RiskReport', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'BankAccountAutoAssignmentConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanDisbursements', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'EntityAccess', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Nbfc', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'DerivedRatios', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Document', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'TaxReturn', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Login', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Scorecard', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'CreditFactor', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Covenant', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Audit', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'PartnerMonitor', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'FixedDeposit', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'PaymentRequest', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'AllLedgers', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'AssetConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Correspondence', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'MiscellaneousConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Checklist', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Nach', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'RiskMonitoring', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'UnderwritingReport', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'CallRecord', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'BankingMetrics', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Anchor', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanSheet', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'KycTracker', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Asset', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanLedgers', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanLcBoe', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Insurance', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Reports', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanApplication', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Bonds', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'NegativeBeneficiary', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Ecl', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'UnverifiedDocs', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanSecurity', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanDocuments', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'CreditRating', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'RequestForDisbursal', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanLap', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'BankAccount', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'ScfAnchorOpportunity', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Salesobservation', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'NbfcPartner', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'ProcessCibilData', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanCorrespondence', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'EmiSchedule', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'IncomingInvoice', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'AssetLiability', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Task', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Dsa', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Hypothecation', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'InsuranceManagement', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'ClientLoanSheet', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'OfferTermsAndConditions', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanBg', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Loan', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'DocumentType', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LegalContract', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'FloatingRates', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'DisbursementDocuments', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Lender', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanApplicationContact', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Client', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'SalesRegister', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'EquifaxPermission', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'AdhocAutoApprovalConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'ScfAnchor', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanAutoApprovalConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'VendorPaymentRequest', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'ReportsStats', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'KycConfig', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'DsaPayoutPaymentRequest', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Fldg', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Approval', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'FinancialMetrics', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'JobMonitor', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Probe', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanLC', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Underwriting', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Form', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Pd', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanRequest', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Cheque', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Invoice', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanPostSanctionChecklist', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'LoanLimitUtilisation', false),
	('OXYZOFINANCESERVICES', 'Oxyzo Financial Services', 'OXYZO', 'Oxyzo', 'Other', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'RFQ', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Order', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Dispatch', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Shipment', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Invoice', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Supplier PO Verification', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Report', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Receipt', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Payment Request', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Ledger', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Voucher', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Invoice Verification', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Warehouse', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Incoming Invoice', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Categories', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Brand', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Product', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Bulk Order', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Jobwork', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Work Order', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Payment Tracker', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Configurations', false),
	('OFGOODS', 'OfGoods', 'OCEAN', 'Ocean', 'Other', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'PartnerConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'EscrowDocuments', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'FactoringInvoice', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LenderPaymentRequest', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'NamespacePermission', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanApplicationCorrespondence', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'OxyzoDocESign', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Feedback', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'NodeSubnodeConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'GstReturnSalesData', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'BankAlertPayment', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Promoter', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanCollections', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'ScfAnchorVendorMapping', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'OfferTnc', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Dashboard', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Module', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'RbiDirectiveMIS', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'AdhocLimit', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'PhysicalDocumentStorage', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Repos', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'RiskReport', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'BankAccountAutoAssignmentConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanDisbursements', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'EntityAccess', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Nbfc', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'DerivedRatios', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Document', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'TaxReturn', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Login', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Scorecard', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'CreditFactor', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Covenant', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Audit', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'PartnerMonitor', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'FixedDeposit', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'PaymentRequest', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'AllLedgers', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'AssetConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Correspondence', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'MiscellaneousConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Checklist', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Nach', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'RiskMonitoring', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'UnderwritingReport', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'CallRecord', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'BankingMetrics', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Anchor', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanSheet', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'KycTracker', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Asset', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanLedgers', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanLcBoe', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Insurance', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Reports', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanApplication', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Bonds', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'NegativeBeneficiary', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Ecl', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'UnverifiedDocs', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanSecurity', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanDocuments', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'CreditRating', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'RequestForDisbursal', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanLap', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'BankAccount', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'ScfAnchorOpportunity', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Salesobservation', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'NbfcPartner', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'ProcessCibilData', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanCorrespondence', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'EmiSchedule', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'IncomingInvoice', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'AssetLiability', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Task', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Dsa', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Hypothecation', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'InsuranceManagement', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'ClientLoanSheet', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'OfferTermsAndConditions', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanBg', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Loan', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'DocumentType', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LegalContract', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'FloatingRates', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'DisbursementDocuments', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Lender', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanApplicationContact', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Client', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'SalesRegister', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'EquifaxPermission', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'AdhocAutoApprovalConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'ScfAnchor', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanAutoApprovalConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'VendorPaymentRequest', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'ReportsStats', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'KycConfig', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'DsaPayoutPaymentRequest', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Fldg', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Approval', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'FinancialMetrics', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'JobMonitor', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Probe', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanLC', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Underwriting', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Form', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Pd', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanRequest', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Cheque', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Invoice', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanPostSanctionChecklist', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'LoanLimitUtilisation', false),
	('OFGOODS', 'OfGoods', 'PRISM', 'Prism', 'Other', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'RFQ', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Order', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Dispatch', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Shipment', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Invoice', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Supplier PO Verification', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Report', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Receipt', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Payment Request', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Ledger', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Voucher', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Invoice Verification', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Warehouse', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Incoming Invoice', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Categories', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Brand', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Product', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Bulk Order', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Jobwork', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Work Order', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Payment Tracker', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Configurations', false),
	('OAGRIFARM', 'OAgriFarm', 'CERES', 'Ceres', 'Other', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'PartnerConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'EscrowDocuments', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'FactoringInvoice', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LenderPaymentRequest', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'NamespacePermission', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanApplicationCorrespondence', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'OxyzoDocESign', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Feedback', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'NodeSubnodeConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'GstReturnSalesData', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'BankAlertPayment', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Promoter', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanCollections', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'ScfAnchorVendorMapping', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'OfferTnc', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Dashboard', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Module', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'RbiDirectiveMIS', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'AdhocLimit', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'PhysicalDocumentStorage', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Repos', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'RiskReport', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'BankAccountAutoAssignmentConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanDisbursements', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'EntityAccess', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Nbfc', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'DerivedRatios', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Document', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'TaxReturn', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Login', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Scorecard', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'CreditFactor', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Covenant', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Audit', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'PartnerMonitor', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'FixedDeposit', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'PaymentRequest', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'AllLedgers', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'AssetConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Correspondence', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'MiscellaneousConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Checklist', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Nach', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'RiskMonitoring', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'UnderwritingReport', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'CallRecord', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'BankingMetrics', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Anchor', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanSheet', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'KycTracker', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Asset', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanLedgers', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanLcBoe', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Insurance', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Reports', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanApplication', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Bonds', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'NegativeBeneficiary', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Ecl', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'UnverifiedDocs', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanSecurity', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanDocuments', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'CreditRating', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'RequestForDisbursal', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanLap', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'BankAccount', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'ScfAnchorOpportunity', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Salesobservation', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'NbfcPartner', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'ProcessCibilData', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanCorrespondence', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'EmiSchedule', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'IncomingInvoice', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'AssetLiability', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Task', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Dsa', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Hypothecation', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'InsuranceManagement', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'ClientLoanSheet', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'OfferTermsAndConditions', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanBg', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Loan', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'DocumentType', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LegalContract', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'FloatingRates', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'DisbursementDocuments', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Lender', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanApplicationContact', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Client', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'SalesRegister', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'EquifaxPermission', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'AdhocAutoApprovalConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'ScfAnchor', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanAutoApprovalConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'VendorPaymentRequest', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'ReportsStats', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'KycConfig', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'DsaPayoutPaymentRequest', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Fldg', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Approval', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'FinancialMetrics', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'JobMonitor', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Probe', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanLC', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Underwriting', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Form', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Pd', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanRequest', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Cheque', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Invoice', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanPostSanctionChecklist', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'LoanLimitUtilisation', false),
	('OAGRIFARM', 'OAgriFarm', 'OAGRIFARMLOAN', 'Oagrifarm (Loan)', 'Other', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'RFQ', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Order', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Dispatch', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Shipment', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Invoice', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Supplier PO Verification', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Report', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Receipt', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Payment Request', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Ledger', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Voucher', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Invoice Verification', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Warehouse', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Incoming Invoice', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Bulk Order', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Jobwork', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Work Order', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Payment Tracker', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Configurations', false),
	('OMAT', 'Omat', 'OMAT', 'Omat', 'Other', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'PartnerConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'EscrowDocuments', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'FactoringInvoice', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LenderPaymentRequest', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'NamespacePermission', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanApplicationCorrespondence', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'OxyzoDocESign', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Feedback', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'NodeSubnodeConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'GstReturnSalesData', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'BankAlertPayment', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Promoter', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanCollections', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'ScfAnchorVendorMapping', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'OfferTnc', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Dashboard', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Module', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'RbiDirectiveMIS', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'AdhocLimit', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'PhysicalDocumentStorage', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Repos', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'RiskReport', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'BankAccountAutoAssignmentConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanDisbursements', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'EntityAccess', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Nbfc', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'DerivedRatios', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Document', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'TaxReturn', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Login', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Scorecard', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'CreditFactor', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Covenant', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Audit', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'PartnerMonitor', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'FixedDeposit', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'PaymentRequest', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'AllLedgers', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'AssetConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Correspondence', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'MiscellaneousConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Checklist', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Nach', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'RiskMonitoring', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Module2', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'UnderwritingReport', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'CallRecord', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'BankingMetrics', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Anchor', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanSheet', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'KycTracker', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Asset', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanLedgers', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanLcBoe', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Insurance', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Reports', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanApplication', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Bonds', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'NegativeBeneficiary', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Ecl', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'UnverifiedDocs', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanSecurity', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanDocuments', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'CreditRating', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'RequestForDisbursal', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanLap', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'BankAccount', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'ScfAnchorOpportunity', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Salesobservation', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'NbfcPartner', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'ProcessCibilData', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanCorrespondence', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'EmiSchedule', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'IncomingInvoice', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'AssetLiability', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Task', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Dsa', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Hypothecation', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'InsuranceManagement', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'ClientLoanSheet', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'OfferTermsAndConditions', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanBg', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Loan', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'DocumentType', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LegalContract', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'FloatingRates', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'DisbursementDocuments', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Lender', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanApplicationContact', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Client', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'SalesRegister', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'EquifaxPermission', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'AdhocAutoApprovalConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'ScfAnchor', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanAutoApprovalConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'VendorPaymentRequest', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'ReportsStats', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'KycConfig', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'DsaPayoutPaymentRequest', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Fldg', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Approval', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'FinancialMetrics', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'JobMonitor', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Probe', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanLC', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Underwriting', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Form', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Pd', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanRequest', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Cheque', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'Invoice', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanPostSanctionChecklist', false),
	('OMAT', 'Omat', 'OMAT_FINANCE', 'Omat Finance', 'LoanLimitUtilisation', false);

--	Form_label fields
	INSERT INTO form_label (field_key, label, position) VALUES ('subDepartment', 'Sub-Department', 'header');
    INSERT INTO form_label (field_key, label, position) VALUES ('employeeCompany', 'Company Name', 'header');
    INSERT INTO form_label (field_key, label, position) VALUES ('employeeName', 'Employee Name', 'header');
    INSERT INTO form_label (field_key, label, position) VALUES ('dateCreated', 'Date Created', 'labelChips');
    INSERT INTO form_label (field_key, label, position) VALUES ('emailId', 'Email Id', 'labelChips');
    INSERT INTO form_label (field_key, label, position) VALUES ('approvalStatus', 'Manager Status', 'labelChips');
    INSERT INTO form_label (field_key, label, position) VALUES ('controlTowerStatus', 'Control Tower Status', 'labelChips');
    INSERT INTO form_label (field_key, label, position) VALUES ('dateApproved', 'Date Approved', 'labelChips');
    INSERT INTO form_label (field_key, label, position) VALUES ('approveRemarks', 'Manager Remarks', 'footer');
    INSERT INTO form_label (field_key, label, position) VALUES ('dateCompleted', 'Date Completed', 'labelChips');
    INSERT INTO form_label (field_key, label, position) VALUES ('reviewRemarks', 'Review Remarks', 'footer');
    INSERT INTO form_label (field_key, label, position) VALUES ('requestRemarks', 'Request Remarks', 'footer');
    INSERT INTO form_label (field_key, label, position) VALUES ('modules', 'Modules', 'body');